apiVersion: v1
kind: Service
metadata:
  name: ogba-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - targetPort: 8080 # Container port
      port: 8070 # Our kubernetes service port
      nodePort: 32020 # 32000 - 32767 Host port for us to access our application on the web
