apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app
  namespace: Dev
spec:
  updatePolicy:
    updateMode: "off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myapp
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 500m
          memory: 1024Mi
        controlledResources: ["cpu", "memory"]
