name: Cohort16 Continous Integration

on:
    push:
      branches: 
        - main

jobs:
  build-deploy:
    name: Build A Project
    runs-on: Ubuntu-latest

    steps:
      - name: Repo Check out
        uses: actions/checkout@v4

      - name: JAVA installation
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: 17

      - name: Maven installation
        run: mvn -B test --file pom.xml

      - name: Code build
        run: |
          mvn clean
          mvn package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ch16:latest




