name: Dev & QA jobs # the name of your pipeline

on: # triggers of your github action run
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Building Artifact
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: JDK 17 Setup
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Unit Testing
        run: mvn -B test --file pom.xml # Tests maven with the repo to ensure everything is right with the pom.xml, -B prevents interraction

      - name: Building Artifact
        run: | # Use this pipe command if you want to run multiple commands
          mvn clean
          mvn package

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zeus -Dsonar.projectName='zeus'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # choose read,write,delete

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/manorapp:latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/manorapp:latest
          # secrets: |                                      #use this for private repo
          #   GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

      - name: Build Docker image
        run: |
          docker pull zeusmanor/tomcat:latest  # Pull your custom Tomcat image from Docker Hub

      - name: Deploy WAR to Docker Tomcat
        run: |
          docker run -d -p 8080:8080 -v ${{ github.workspace }}/target/your-app.war:/usr/local/tomcat/webapps/your-app.war zeusmanor/tomcat:latest
