name: Build and deploy my APP # the name of your pipeline

on: # triggers of your github action run
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Building Artifact
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4
